{
  "ID": "63bc58b7-406c-4cb7-9710-d1b7ca349eb9",
  "Root": {
    "alive": true,
    "content": [
      "593bc2f4-d458-4c6a-95c1-b48b902cebb1",
      "43e5d4db-5025-4ccd-857d-8fdeebb1a33a"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1551950662450,
    "format": {
      "page_full_width": true,
      "page_small_text": true
    },
    "id": "63bc58b7-406c-4cb7-9710-d1b7ca349eb9",
    "ignore_block_count": true,
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1551950662450,
    "parent_id": "fb28bc7f-e61f-4ac8-b19d-4670cd051e98",
    "parent_table": "block",
    "properties": {
      "title": [
        [
          "Throwing an exception from a different method while preserving its information"
        ]
      ]
    },
    "type": "page",
    "version": 3,
    "content_resolved": [
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1551950662449,
        "id": "593bc2f4-d458-4c6a-95c1-b48b902cebb1",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1551950662449,
        "parent_id": "63bc58b7-406c-4cb7-9710-d1b7ca349eb9",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Occasionally you’d want to catch an exception and throw it from a different thread or method while preserving the original exception stack. This can be done with "
            ],
            [
              "ExceptionDispatchInfo",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              ":"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "Occasionally you’d want to catch an exception and throw it from a different thread or method while preserving the original exception stack. This can be done with "
          },
          {
            "Text": "ExceptionDispatchInfo",
            "AttrFlags": 2
          },
          {
            "Text": ":"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1551950662450,
        "id": "43e5d4db-5025-4ccd-857d-8fdeebb1a33a",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1551950662450,
        "parent_id": "63bc58b7-406c-4cb7-9710-d1b7ca349eb9",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "using System.Runtime.ExceptionServices;\n\nvoid Main()\n{\n    ExceptionDispatchInfo capturedException = null;\n    try\n    {\n        throw new Exception();\n    }\n    catch (Exception ex)\n    {\n        capturedException = ExceptionDispatchInfo.Capture(ex);\n    }\n    \n    Foo(capturedException);\n}\n\nvoid Foo(ExceptionDispatchInfo exceptionDispatchInfo)\n{\n    // Do stuff\n\n    if (capturedException != null)\n    {\n        // Exception stack trace will show it was thrown from Main() and not from Foo()\n        exceptionDispatchInfo.Throw();\n    }\n}"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "using System.Runtime.ExceptionServices;\n\nvoid Main()\n{\n    ExceptionDispatchInfo capturedException = null;\n    try\n    {\n        throw new Exception();\n    }\n    catch (Exception ex)\n    {\n        capturedException = ExceptionDispatchInfo.Capture(ex);\n    }\n    \n    Foo(capturedException);\n}\n\nvoid Foo(ExceptionDispatchInfo exceptionDispatchInfo)\n{\n    // Do stuff\n\n    if (capturedException != null)\n    {\n        // Exception stack trace will show it was thrown from Main() and not from Foo()\n        exceptionDispatchInfo.Throw();\n    }\n}",
        "code_language": "Plain Text"
      }
    ],
    "title": "Throwing an exception from a different method while preserving its information",
    "format_page": {
      "page_cover": "",
      "page_cover_position": 0,
      "page_font": "",
      "page_full_width": true,
      "page_icon": "",
      "page_small_text": true
    }
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "en",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "America/Los_Angeles",
      "version": 18
    }
  ],
  "Tables": null
}