{
  "ID": "a355ba35-854c-4541-9574-c35d8ddc8f46",
  "Root": {
    "alive": true,
    "content": [
      "e37f1de5-08bb-4459-991a-6bc01f9c8f26",
      "7b285d74-1907-45bb-8a53-ada151bc564b",
      "7265c181-9331-4152-b91a-ace20441c51d",
      "426f1cc1-3ed4-4fc1-b1d5-2b75b2977546",
      "fbe938c2-6ea9-4763-ac31-22f3579fdcc6",
      "8c54969a-4bf8-4136-9d75-2c7c9f295ca8",
      "f310daac-24c7-455c-93d3-3539c07f7eff",
      "76f753bf-ac5b-4e07-91b8-ef142347ee9a",
      "e6d4a738-0c18-4006-b9fa-393666483c6f",
      "fa637137-aa37-4d56-9b45-9b7522f8ef1d",
      "7636940f-8db3-4ab4-83f2-b41f94cda459",
      "314f836b-a245-42cc-8e46-e89bad4dad2d",
      "4b989ec3-1850-4702-8723-5a4facc8cb23",
      "6a4a0b29-d7d9-42f8-b568-ae7084d7b019",
      "9d1670d9-37e1-47ce-84c8-22082a8fe51a",
      "84301dad-5fac-4915-b118-a72817292c0c",
      "440680a9-e105-4ee0-9e14-c7007791c439"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1550518004890,
    "format": {
      "page_full_width": true,
      "page_small_text": true
    },
    "id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
    "ignore_block_count": true,
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1550518004890,
    "parent_id": "65b3b4cb-dbb9-4dfb-9c83-9429dfa4e76a",
    "parent_table": "block",
    "properties": {
      "title": [
        [
          "Pitfall - Throwing Throwable Exception Error or RuntimeException"
        ]
      ]
    },
    "type": "page",
    "version": 3,
    "content_resolved": [
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004884,
        "id": "e37f1de5-08bb-4459-991a-6bc01f9c8f26",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004884,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "While catching the "
            ],
            [
              "Throwable",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              ", "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              ", "
            ],
            [
              "Error",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " and "
            ],
            [
              "RuntimeException",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " exceptions is bad, throwing them is even worse."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "While catching the "
          },
          {
            "Text": "Throwable",
            "AttrFlags": 2
          },
          {
            "Text": ", "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": ", "
          },
          {
            "Text": "Error",
            "AttrFlags": 2
          },
          {
            "Text": " and "
          },
          {
            "Text": "RuntimeException",
            "AttrFlags": 2
          },
          {
            "Text": " exceptions is bad, throwing them is even worse."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004886,
        "id": "7b285d74-1907-45bb-8a53-ada151bc564b",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004886,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "The basic problem is that when your application needs to handle exceptions, the presence of the top level exceptions make it hard to discriminate between different error conditions. For example"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "The basic problem is that when your application needs to handle exceptions, the presence of the top level exceptions make it hard to discriminate between different error conditions. For example"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004886,
        "id": "7265c181-9331-4152-b91a-ace20441c51d",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004886,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "try {\n    InputStream is = new FileInputStream(someFile);  // could throw IOException\n    ...\n    if (somethingBad) {\n        throw new Exception();  // WRONG\n    }\n} catch (IOException ex) {\n    System.err.println(\"cannot open ...\");\n} catch (Exception ex) {\n    System.err.println(\"something bad happened\");  // WRONG\n}"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "try {\n    InputStream is = new FileInputStream(someFile);  // could throw IOException\n    ...\n    if (somethingBad) {\n        throw new Exception();  // WRONG\n    }\n} catch (IOException ex) {\n    System.err.println(\"cannot open ...\");\n} catch (Exception ex) {\n    System.err.println(\"something bad happened\");  // WRONG\n}",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004886,
        "id": "426f1cc1-3ed4-4fc1-b1d5-2b75b2977546",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004886,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "The problem is that because we threw an "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " instance, we are forced to catch it. However as described in another example, catching "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " is bad. In this situation, it becomes difficult to discriminate between the “expected” case of an "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " that gets thrown if "
            ],
            [
              "somethingBad",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " is "
            ],
            [
              "true",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              ", and the unexpected case where we actually catch an unchecked exception such as "
            ],
            [
              "NullPointerException",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              "."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "The problem is that because we threw an "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " instance, we are forced to catch it. However as described in another example, catching "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " is bad. In this situation, it becomes difficult to discriminate between the “expected” case of an "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " that gets thrown if "
          },
          {
            "Text": "somethingBad",
            "AttrFlags": 2
          },
          {
            "Text": " is "
          },
          {
            "Text": "true",
            "AttrFlags": 2
          },
          {
            "Text": ", and the unexpected case where we actually catch an unchecked exception such as "
          },
          {
            "Text": "NullPointerException",
            "AttrFlags": 2
          },
          {
            "Text": "."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004887,
        "id": "fbe938c2-6ea9-4763-ac31-22f3579fdcc6",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004887,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "If the top-level exception is allowed to propagate, we run into other problems:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "If the top-level exception is allowed to propagate, we run into other problems:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004887,
        "id": "8c54969a-4bf8-4136-9d75-2c7c9f295ca8",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004887,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "We now have to remember all of the different reasons that we threw the top-level, and discriminate / handle them."
            ]
          ]
        },
        "type": "bulleted_list",
        "version": 1,
        "inline_content": [
          {
            "Text": "We now have to remember all of the different reasons that we threw the top-level, and discriminate / handle them."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004888,
        "id": "f310daac-24c7-455c-93d3-3539c07f7eff",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004888,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "In the case of "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " and "
            ],
            [
              "Throwable",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " we also need to add these exceptions to the "
            ],
            [
              "throws",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " clause of methods if we want the exception to propagate. This is problematic, as described below."
            ]
          ]
        },
        "type": "bulleted_list",
        "version": 1,
        "inline_content": [
          {
            "Text": "In the case of "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " and "
          },
          {
            "Text": "Throwable",
            "AttrFlags": 2
          },
          {
            "Text": " we also need to add these exceptions to the "
          },
          {
            "Text": "throws",
            "AttrFlags": 2
          },
          {
            "Text": " clause of methods if we want the exception to propagate. This is problematic, as described below."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004888,
        "id": "76f753bf-ac5b-4e07-91b8-ef142347ee9a",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004888,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "In short, don’t throw these exceptions. Throw a more specific exception that more closely describes the “exceptional event” that has happened. If you need to, define and use a custom exception class."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "In short, don’t throw these exceptions. Throw a more specific exception that more closely describes the “exceptional event” that has happened. If you need to, define and use a custom exception class."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004888,
        "id": "e6d4a738-0c18-4006-b9fa-393666483c6f",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004888,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Declaring Throwable or Exception in a method’s “throws” is problematic."
            ]
          ]
        },
        "type": "sub_header",
        "version": 1,
        "inline_content": [
          {
            "Text": "Declaring Throwable or Exception in a method’s “throws” is problematic."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004888,
        "id": "fa637137-aa37-4d56-9b45-9b7522f8ef1d",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004888,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "It is tempting to replace a long list of thrown exceptions in a method’s "
            ],
            [
              "throws",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " clause with "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " or even `Throwable. This is a bad idea:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "It is tempting to replace a long list of thrown exceptions in a method’s "
          },
          {
            "Text": "throws",
            "AttrFlags": 2
          },
          {
            "Text": " clause with "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " or even `Throwable. This is a bad idea:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004888,
        "id": "7636940f-8db3-4ab4-83f2-b41f94cda459",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004888,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "It forces the caller to handle (or propagate) "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              "."
            ]
          ]
        },
        "type": "numbered_list",
        "version": 1,
        "inline_content": [
          {
            "Text": "It forces the caller to handle (or propagate) "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": "."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004889,
        "id": "314f836b-a245-42cc-8e46-e89bad4dad2d",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004889,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "We can no longer rely on the compiler to tell us about specific checked exceptions that need to be handled."
            ]
          ]
        },
        "type": "numbered_list",
        "version": 1,
        "inline_content": [
          {
            "Text": "We can no longer rely on the compiler to tell us about specific checked exceptions that need to be handled."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004889,
        "id": "4b989ec3-1850-4702-8723-5a4facc8cb23",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004889,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Handling "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " properly is difficult. It is hard to know what actual exceptions may be caught, and if you don’t know what could be caught, it is hard to know what recovery strategy is appropriate."
            ]
          ]
        },
        "type": "numbered_list",
        "version": 1,
        "inline_content": [
          {
            "Text": "Handling "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " properly is difficult. It is hard to know what actual exceptions may be caught, and if you don’t know what could be caught, it is hard to know what recovery strategy is appropriate."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004889,
        "id": "6a4a0b29-d7d9-42f8-b568-ae7084d7b019",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004889,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "Handling "
            ],
            [
              "Throwable",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " is even harder, since now you also have to cope with potential failures that should never be recovered from."
            ]
          ]
        },
        "type": "numbered_list",
        "version": 1,
        "inline_content": [
          {
            "Text": "Handling "
          },
          {
            "Text": "Throwable",
            "AttrFlags": 2
          },
          {
            "Text": " is even harder, since now you also have to cope with potential failures that should never be recovered from."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004889,
        "id": "9d1670d9-37e1-47ce-84c8-22082a8fe51a",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004889,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "This advice means that certain other patterns should be avoided. For example:"
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "This advice means that certain other patterns should be avoided. For example:"
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004889,
        "id": "84301dad-5fac-4915-b118-a72817292c0c",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004889,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "try {\n    doSomething();\n} catch (Exception ex) {\n    report(ex);\n    throw ex;\n}"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "try {\n    doSomething();\n} catch (Exception ex) {\n    report(ex);\n    throw ex;\n}",
        "code_language": "Plain Text"
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550518004890,
        "id": "440680a9-e105-4ee0-9e14-c7007791c439",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550518004890,
        "parent_id": "a355ba35-854c-4541-9574-c35d8ddc8f46",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "The above attempts to log all exceptions as they pass, without definitively handling them. Unfortunately, prior to Java 7, the "
            ],
            [
              "throw ex;",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " statement caused the compiler to think that any "
            ],
            [
              "Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " could be thrown. That could force you to declare the enclosing method as "
            ],
            [
              "throws Exception",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              ". From Java 7 onwards, the compiler knows that the set of exceptions that could be (re-thrown) there is smaller."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "The above attempts to log all exceptions as they pass, without definitively handling them. Unfortunately, prior to Java 7, the "
          },
          {
            "Text": "throw ex;",
            "AttrFlags": 2
          },
          {
            "Text": " statement caused the compiler to think that any "
          },
          {
            "Text": "Exception",
            "AttrFlags": 2
          },
          {
            "Text": " could be thrown. That could force you to declare the enclosing method as "
          },
          {
            "Text": "throws Exception",
            "AttrFlags": 2
          },
          {
            "Text": ". From Java 7 onwards, the compiler knows that the set of exceptions that could be (re-thrown) there is smaller."
          }
        ]
      }
    ],
    "title": "Pitfall - Throwing Throwable Exception Error or RuntimeException",
    "format_page": {
      "page_cover": "",
      "page_cover_position": 0,
      "page_font": "",
      "page_full_width": true,
      "page_icon": "",
      "page_small_text": true
    }
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "en",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "America/Los_Angeles",
      "version": 18
    }
  ],
  "Tables": null
}