{
  "ID": "bb4bcd3a-be9b-4ce5-b300-548d8382bf2c",
  "Root": {
    "alive": true,
    "content": [
      "68884300-278d-4be2-89ad-8985ca74ac3b",
      "e22fe1f9-7f54-476b-8e7b-302a9680b89f"
    ],
    "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "created_time": 1550524663515,
    "id": "bb4bcd3a-be9b-4ce5-b300-548d8382bf2c",
    "ignore_block_count": true,
    "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
    "last_edited_time": 1550524663515,
    "parent_id": "52470773-ddd6-4b1b-ad39-7b26f7b28f00",
    "parent_table": "block",
    "properties": {
      "title": [
        [
          "090 try"
        ]
      ]
    },
    "type": "page",
    "version": 1,
    "content_resolved": [
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550524663513,
        "id": "68884300-278d-4be2-89ad-8985ca74ac3b",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550524663513,
        "parent_id": "bb4bcd3a-be9b-4ce5-b300-548d8382bf2c",
        "parent_table": "block",
        "properties": {
          "title": [
            [
              "The keyword "
            ],
            [
              "try",
              [
                [
                  "c"
                ]
              ]
            ],
            [
              " is followed by a block, or by a constructor initializer list and then a block (see "
            ],
            [
              "here",
              [
                [
                  "a",
                  "http://stackoverflow.com/documentation/c%2B%2B/1354/exceptions/6692/function-try-blocks-in-constructor"
                ]
              ]
            ],
            [
              "). The try block is followed by one or more "
            ],
            [
              "catch blocks",
              [
                [
                  "a",
                  "http://stackoverflow.com/documentation/c%2B%2B/4891/keywords/18492/catch"
                ]
              ]
            ],
            [
              ". If an "
            ],
            [
              "exception",
              [
                [
                  "a",
                  "http://stackoverflow.com/documentation/c%2B%2B/1354/exceptions"
                ]
              ]
            ],
            [
              " propagates out of the try block, each of the corresponding catch blocks after the try block has the opportunity to handle the exception, if the types match."
            ]
          ]
        },
        "type": "text",
        "version": 1,
        "inline_content": [
          {
            "Text": "The keyword "
          },
          {
            "Text": "try",
            "AttrFlags": 2
          },
          {
            "Text": " is followed by a block, or by a constructor initializer list and then a block (see "
          },
          {
            "Text": "here",
            "Link": "http://stackoverflow.com/documentation/c%2B%2B/1354/exceptions/6692/function-try-blocks-in-constructor"
          },
          {
            "Text": "). The try block is followed by one or more "
          },
          {
            "Text": "catch blocks",
            "Link": "http://stackoverflow.com/documentation/c%2B%2B/4891/keywords/18492/catch"
          },
          {
            "Text": ". If an "
          },
          {
            "Text": "exception",
            "Link": "http://stackoverflow.com/documentation/c%2B%2B/1354/exceptions"
          },
          {
            "Text": " propagates out of the try block, each of the corresponding catch blocks after the try block has the opportunity to handle the exception, if the types match."
          }
        ]
      },
      {
        "alive": true,
        "created_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "created_time": 1550524663514,
        "id": "e22fe1f9-7f54-476b-8e7b-302a9680b89f",
        "ignore_block_count": true,
        "last_edited_by": "bb760e2d-d679-4b64-b2a9-03005b21870a",
        "last_edited_time": 1550524663514,
        "parent_id": "bb4bcd3a-be9b-4ce5-b300-548d8382bf2c",
        "parent_table": "block",
        "properties": {
          "language": [
            [
              "Plain Text"
            ]
          ],
          "title": [
            [
              "std::vector\u003cint\u003e v(N);     // if an exception is thrown here,\n                           // it will not be caught by the following catch block\ntry {\n    std::vector\u003cint\u003e v(N); // if an exception is thrown here,\n                           // it will be caught by the following catch block\n    // do something with v\n} catch (const std::bad_alloc\u0026) {\n    // handle bad_alloc exceptions from the try block\n}"
            ]
          ]
        },
        "type": "code",
        "version": 1,
        "code": "std::vector\u003cint\u003e v(N);     // if an exception is thrown here,\n                           // it will not be caught by the following catch block\ntry {\n    std::vector\u003cint\u003e v(N); // if an exception is thrown here,\n                           // it will be caught by the following catch block\n    // do something with v\n} catch (const std::bad_alloc\u0026) {\n    // handle bad_alloc exceptions from the try block\n}",
        "code_language": "Plain Text"
      }
    ],
    "title": "090 try"
  },
  "Users": [
    {
      "email": "kkowalczyk@gmail.com",
      "family_name": "Kowalczyk",
      "given_name": "Krzysztof",
      "id": "bb760e2d-d679-4b64-b2a9-03005b21870a",
      "locale": "en",
      "mobile_onboarding_completed": true,
      "onboarding_completed": true,
      "profile_photo": "https://s3-us-west-2.amazonaws.com/public.notion-static.com/2dcaa66c-7674-4ff6-9924-601785b63561/head-bw-640x960.png",
      "time_zone": "America/Los_Angeles",
      "version": 18
    }
  ],
  "Tables": null
}